version: '2'

networks:
  mesosnet:
    driver: bridge

volumes:
  certs:

services:
  proxy:
    image: wrouesnel/docker-squid4
    environment:
      DISABLE_CACHE: "yes"
    ports:
    - 127.0.0.1:3128:3128
    networks:
      mesosnet:

  makecerts:
    build:
      context: certtool
    command: --CN=mesos-in-docker
             --emails=w.rouesnel@gmail.com
             mesos-master-1
             mesos-master-2
             mesos-master-3
             mesos-agent-1
             marathon
             client
    volumes:
    - certs:/certs

  etcd0:
    image: quay.io/coreos/etcd
    command: |
             etcd --name etcd0
             --advertise-client-urls http://etcd0:2379
             --listen-client-urls http://0.0.0.0:2379
             --initial-advertise-peer-urls http://etcd0:2380
             --listen-peer-urls http://0.0.0.0:2380
             --initial-cluster-token mesos-in-docker
             --initial-cluster etcd0=http://etcd0:2380
             --initial-cluster-state new
             --debug
    networks:
      mesosnet:

  zetcd0:
    build: 
      context: zetcd
    command: -endpoint=http://etcd0:2379 -zkaddr=:2181 -logtostderr
    networks:
      mesosnet:
    depends_on:
    - etcd0

  mesos-master-1:
    build: 
      context: docker
      args:
        http_proxy: ${http_proxy}
    command: mesos-master --work_dir=/var/lib/mesos 
                --zk=zk://zetcd0:2181/mesos --quorum=2
                --no-hostname_lookup --hostname=mesos-master-1
    restart: always
    environment:
      LIBPROCESS_SSL_ENABLED: "true"
      LIBPROCESS_SSL_SUPPORT_DOWNGRADE: "false"
      LIBPROCESS_SSL_KEY_FILE: /certs/mesos-master-1.pem
      LIBPROCESS_SSL_CERT_FILE: /certs/mesos-master-1.crt
      LIBPROCESS_SSL_VERIFY_CERT: "true"
      LIBPROCESS_SSL_REQUIRE_CERT: "true"
      LIBPROCESS_SSL_VERIFY_IPADD: "false"
      LIBPROCESS_SSL_CA_FILE: /certs/mesos-in-docker.crt
      LIBPROCESS_SSL_ENABLE_SSL_V3: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_0: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_1: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_2: "true"
    volumes:
    - certs:/certs
    networks:
      mesosnet:
      
  mesos-master-2:
    build: 
      context: docker
      args:
        http_proxy: ${http_proxy}
    command: mesos-master --work_dir=/var/lib/mesos 
                --zk=zk://zetcd0:2181/mesos --quorum=2
                --no-hostname_lookup --hostname=mesos-master-2
    restart: always
    environment:
      LIBPROCESS_SSL_ENABLED: "true"
      LIBPROCESS_SSL_SUPPORT_DOWNGRADE: "false"
      LIBPROCESS_SSL_KEY_FILE: /certs/mesos-master-2.pem
      LIBPROCESS_SSL_CERT_FILE: /certs/mesos-master-2.crt
      LIBPROCESS_SSL_VERIFY_CERT: "true"
      LIBPROCESS_SSL_REQUIRE_CERT: "true"
      LIBPROCESS_SSL_VERIFY_IPADD: "false"
      LIBPROCESS_SSL_CA_FILE: /certs/mesos-in-docker.crt
      LIBPROCESS_SSL_ENABLE_SSL_V3: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_0: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_1: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_2: "true"
    volumes:
    - certs:/certs
    networks:
      mesosnet:
      
  mesos-master-3:
    build: 
      context: docker
      args:
        http_proxy: ${http_proxy}
    command: mesos-master --work_dir=/var/lib/mesos 
                --zk=zk://zetcd0:2181/mesos --quorum=2
                --no-hostname_lookup --hostname=mesos-master-3
    restart: always
    environment:
      LIBPROCESS_SSL_ENABLED: "true"
      LIBPROCESS_SSL_SUPPORT_DOWNGRADE: "false"
      LIBPROCESS_SSL_KEY_FILE: /certs/mesos-master-3.pem
      LIBPROCESS_SSL_CERT_FILE: /certs/mesos-master-3.crt
      LIBPROCESS_SSL_VERIFY_CERT: "true"
      LIBPROCESS_SSL_REQUIRE_CERT: "true"
      LIBPROCESS_SSL_VERIFY_IPADD: "false"
      LIBPROCESS_SSL_CA_FILE: /certs/mesos-in-docker.crt
      LIBPROCESS_SSL_ENABLE_SSL_V3: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_0: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_1: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_2: "true"
    volumes:
    - certs:/certs
    networks:
      mesosnet:
  
  mesos-agent-1:
    build: 
      context: docker
      args:
        http_proxy: ${http_proxy}
    privileged: true
    command: mesos-agent
                --work_dir=/var/lib/mesos
                --containerizers=docker
                --master=zk://zetcd0:2181/mesos
                --no-systemd_enable_support
                --no-hostname_lookup
                --hostname=mesos-agent-1
    restart: always
    environment:
      LIBPROCESS_SSL_ENABLED: "true"
      LIBPROCESS_SSL_SUPPORT_DOWNGRADE: "false"
      LIBPROCESS_SSL_KEY_FILE: /certs/mesos-agent-1.pem
      LIBPROCESS_SSL_CERT_FILE: /certs/mesos-agent-1.crt
      LIBPROCESS_SSL_VERIFY_CERT: "true"
      LIBPROCESS_SSL_REQUIRE_CERT: "true"
      LIBPROCESS_SSL_VERIFY_IPADD: "false"
      LIBPROCESS_SSL_CA_FILE: /certs/mesos-in-docker.crt
      LIBPROCESS_SSL_ENABLE_SSL_V3: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_0: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_1: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_2: "true"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker:ro
    - /sys/fs/cgroup:/sys/fs/cgroup
    - certs:/certs
    networks:
      mesosnet:

  marathon:
    image: mesosphere/marathon
    command: --master zk://zetcd0:2181/mesos 
             --zk zk://zetcd0:2181/marathon
             --hostname marathon
    restart: always
    environment:
      LIBPROCESS_SSL_ENABLED: "true"
      LIBPROCESS_SSL_SUPPORT_DOWNGRADE: "false"
      LIBPROCESS_SSL_KEY_FILE: /certs/marathon.pem
      LIBPROCESS_SSL_CERT_FILE: /certs/marathon.crt
      LIBPROCESS_SSL_VERIFY_CERT: "true"
      LIBPROCESS_SSL_REQUIRE_CERT: "true"
      LIBPROCESS_SSL_VERIFY_IPADD: "false"
      LIBPROCESS_SSL_CA_FILE: /certs/mesos-in-docker.crt
      LIBPROCESS_SSL_ENABLE_SSL_V3: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_0: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_1: "false"
      LIBPROCESS_SSL_ENABLE_TLS_V1_2: "true"
    ports:
    - 8080:8080
    networks:
      mesosnet:
